In [1]:
import cv2
vidcap = cv2.VideoCapture('ap2.mp4')
def getFrame(sec):
    vidcap.set(cv2.CAP_PROP_POS_MSEC,sec*1000)
    hasFrames,image = vidcap.read()
    if hasFrames:
        cv2.imwrite("image"+str(count)+".jpg", image)     # save frame as JPG file
    return hasFrames
sec = 0
frameRate = 1.5 #//it will capture image in each 0.5 second
count=1
success = getFrame(sec)
while success:
    count = count + 1
    sec = sec + frameRate
    sec = round(sec, 2)
    success = getFrame(sec)

In [4]:
# import the modules
import os
import cv2
from os import listdir

# get the path/directory
folder_dir = 'C:\\Users\\HP\\OneDrive\\Desktop\\COUNT\\apple\\image1.jpg'
# image = cv2.imread('C:\\Users\\HP\\OneDrive\\Desktop\\COUNT\\apple\\image1.jpg')
for images in os.listdir(folder_dir):

    # check if the image ends with png
    if (images.endswith(".jpg")):
        print(images)


NotADirectoryError: [WinError 267] The directory name is invalid: 'C:\\Users\\HP\\OneDrive\\Desktop\\COUNT\\apple\\image1.jpg'

In [7]:
import cv2 
import os 
import glob 
img_dir = "C:\\Users\\HP\\OneDrive\\Desktop\\COUNT\\apple\\output" # Enter Directory of all images  
data_path = os.path.join(img_dir,'*g') 
files = glob.glob(data_path) 
data = [] 
for f1 in files: 
    img = cv2.imread(f1) 
    data.append(img)
    
for i in data:
    (f"{i}.jpg")

[[[ 18  25  22]
  [ 18  25  22]
  [ 18  25  22]
  ...
  [ 19  43  33]
  [ 28  49  41]
  [ 44  65  57]]

 [[ 16  21  19]
  [ 16  23  20]
  [ 18  25  22]
  ...
  [114 139 129]
  [138 161 153]
  [159 182 174]]

 [[ 16  18  18]
  [ 15  20  19]
  [ 18  24  23]
  ...
  [189 219 208]
  [179 206 196]
  [170 197 187]]

 ...

 [[ 45  44 110]
  [ 65  66 134]
  [113 114 188]
  ...
  [ 16  16  16]
  [ 14  16  16]
  [ 14  16  16]]

 [[ 50  49 121]
  [ 33  35 105]
  [ 40  48 115]
  ...
  [ 17  17  17]
  [ 14  16  16]
  [ 14  16  16]]

 [[163 164 238]
  [ 85  90 159]
  [ 33  42 106]
  ...
  [ 17  17  17]
  [ 15  17  17]
  [ 15  17  17]]].jpg
[[[16 18 48]
  [16 18 48]
  [17 19 53]
  ...
  [28 36 36]
  [27 32 31]
  [28 33 31]]

 [[16 18 48]
  [16 18 48]
  [16 19 50]
  ...
  [30 35 36]
  [30 35 34]
  [31 36 34]]

 [[16 18 48]
  [17 19 49]
  [17 20 51]
  ...
  [28 33 34]
  [33 38 37]
  [34 37 35]]

 ...

 [[24 86 68]
  [30 92 74]
  [35 95 77]
  ...
  [40 52 52]
  [75 84 87]
  [79 91 93]]

 [[24 85 65]
  [

In [2]:
import cv2
import mediapipe
 
drawingModule = mediapipe.solutions.drawing_utils
handsModule = mediapipe.solutions.hands
 
capture = cv2.VideoCapture('ap1.mp4')
 
frameNr = 0
 
with handsModule.Hands() as hands:
 
    while (True):
 
        success, frame = capture.read()
 
        if not success:
            break
 
        results = hands.process(cv2.cvtColor(frame, cv2.COLOR_BGR2RGB))
 
        if results.multi_hand_landmarks != None:
            for handLandmarks in results.multi_hand_landmarks:
                drawingModule.draw_landmarks(frame, handLandmarks, handsModule.HAND_CONNECTIONS)
 
        cv2.imwrite(f'C:/Users/HP/OneDrive/Desktop/COUNT/apple/output/frame_{frameNr}.jpg', frame)
 
        frameNr = frameNr+1
 
capture.release()

In [4]:
from __future__ import division
import io
import os
import random
import cv2
import numpy as np
import time
from copy import deepcopy
kernelOpen=np.ones((5,5))
kernelClose=np.ones((20,20))

# The name of the image file to annotate
i=time.strftime("%d-%m-%y_%H-%M-%S")

# capture image
camera = cv2.VideoCapture(0)
return_value, image = camera.read()
cv2.imwrite(i+'.jpeg', image)
del(camera)
frame=image
edge_img=deepcopy(image)
# finds edges in the input image image and
# marks them in the output map edges
edged = cv2.Canny(edge_img,50,100)
edged = cv2.dilate(edged, None, iterations=1)
edged = cv2.erode(edged, None, iterations=1)
 
# find contours in the edge map
cnts, h = cv2.findContours(edged.copy(), cv2.RETR_EXTERNAL,cv2.CHAIN_APPROX_SIMPLE)

max_contA=cv2.contourArea(cnts[0])
max_cont=max(cnts,key=cv2.contourArea)

for i in range(len(cnts)):
    	x,y,w,h=cv2.boundingRect(max_cont)
    	cv2.rectangle(edge_img,(x,y),(x+w,y+h),(0,0,255), 2)
croppedk=frame[y:y+h,x:x+w]

# Display the fruit 
cv2.imshow('Edges',edge_img)

frame=edge_img

# converting BGR to HSV
hsv = cv2.cvtColor(frame, cv2.COLOR_BGR2HSV)
     
# define range of red color in HSV
lower_red = np.array([0,50,50])
upper_red = np.array([10,255,255])
     
# create a red HSV colour boundary and 
# threshold HSV image
redmask1 = cv2.inRange(hsv, lower_red, upper_red)
    
# define range of red color in HSV
lower_red = np.array([170,50,50])
upper_red = np.array([180,255,255])
     
# create a red HSV colour boundary and 
# threshold HSV image
redmask2 = cv2.inRange(hsv, lower_red, upper_red)
 
redmask=redmask1+redmask2
maskOpen=cv2.morphologyEx(redmask,cv2.MORPH_OPEN,kernelOpen)
maskClose=cv2.morphologyEx(maskOpen,cv2.MORPH_CLOSE,kernelClose)

maskFinal=maskClose
cv2.imshow('Red_Mask:',maskFinal)


cnt_r=0
for r in redmask:
	cnt_r=cnt_r+list(r).count(255)
print ("Redness ",cnt_r)

lower_green=np.array([50,50,50])
upper_green=np.array([70,255,255])
greenmask = cv2.inRange(hsv, lower_green, upper_green)
cv2.imshow('Green_Mask:',greenmask)
cnt_g=0
for g in greenmask:
	cnt_g=cnt_g+list(g).count(255)
print ("Greenness ",cnt_g)

lower_yellow=np.array([20,50,50])
upper_yellow=np.array([30,255,255])
yellowmask = cv2.inRange(hsv, lower_yellow, upper_yellow)
cv2.imshow('Yellow_Mask:',yellowmask)
cnt_y=0
for y in yellowmask:
	cnt_y=cnt_y+list(y).count(255)
print ("Yellowness ",cnt_y)


#Calculate ripeness
tot_area=cnt_r+cnt_y+cnt_g
rperc=cnt_r/tot_area
yperc=cnt_y/tot_area
gperc=cnt_g/tot_area


#Adjust the limits for your fruit
glimit=0.5
ylimit=0.8

if gperc>glimit:
	print ("Low Ripeness")
elif yperc>ylimit:
	print ("High Ripeness")
else:
	print ("Medium Ripeness")
# Wait for any key to close
while True: 
	k = cv2.waitKey(5) & 0xFF
	if k==27:
		break
# De-allocate any associated memory usage
cv2.waitKey(0)
cv2.destroyAllWindows() 




    

Redness  16297
Greenness  391
Yellowness  228
Medium Ripeness


KeyboardInterrupt: 